# Generated by Django 4.2.4 on 2023-12-12 15:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('user', 'followers')},
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('user', 'following')},
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], default='send')),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_set', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reciver', 'sender')},
            },
        ),
    ]
