# Generated by Django 4.2.4 on 2023-12-12 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_followers_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
