# Generated by Django 4.2.4 on 2024-02-09 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
