# Generated by Django 4.2.4 on 2023-12-10 10:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="like",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
            ),
        ),
    ]
